### ISSUE TITLE
Issues found in final OMOP files

### ISSUE THREAD

**Issue by xinyuejohn** [USM-CHU-FGuyon/BlendedICU#14]
Hi, thanks for fixing previous issues in such a prompt time! I also found the other issues.

1. Duplicated rows in person table.
There are several duplicate rows for some specific person_id. Some rows have different records in year_of_birth column.
Here's the example of running only "MIMIC-III" Dataset.
<img width="1349" alt="Screenshot 2024-01-10 at 17 15 57" src="https://github.com/USM-CHU-FGuyon/BlendedICU/assets/88339105/34237700-9d1b-47f2-b9ea-89562b01a611">

2. One concept_id 3711521 couldn't been found in concept table
This concept was used in observation table. I presume it is body weight (group).
<img width="958" alt="Screenshot 2024-01-10 at 17 22 38" src="https://github.com/USM-CHU-FGuyon/BlendedICU/assets/88339105/d3f9fda4-87c8-4f22-83d4-87d76418e755">

3. "unit_source" column in measurement table is not defined in OMOP CDM. It should be named as "unit_source_value"
4. "time" column in measurement table is not defined in OMOP CDM. It should be named as "measurement_time"

Thanks for looking into this!

**Comment by USM-CHU-FGuyon** [comment]
Thanks for this, I will be checking all of it soon !

**Comment by USM-CHU-FGuyon** [comment]
Regarding your last point: 
According to https://ohdsi.github.io/CommonDataModel/cdm53.html#MEASUREMENT `measurement_time` is deprecated and `measurement_datetime` will be required in v6.

These two columns are given in the current `measurement` table.

Because the admission dates are not specified in some of the ICU datasets, I set a reference date (2023-01-01 00:00) for the ICU admission. `measurement_datetimes` prior to that date mean "before admission". Because these dates are artificially added to fit the OMOP requirements, I choose to keep the "seconds since admission" `time` column which is here for convenience. I'm keeping this additional `time` column for now, but feel free to drop it you need to fit more stricly to OMOP standards.

**Comment by xinyuejohn** [comment]
Thanks for pointing out this! So I think I will omit the `time` column for now and only use `measurement_datetimes` since they essentially contain the same information.
