### ISSUE TITLE
MIMIC-III

### ISSUE THREAD

**Issue by Zethson** [USM-CHU-FGuyon/BlendedICU#3]
Hey,

is there a reason why you didn't also add MIMIC-III?

**Comment by USM-CHU-FGuyon** [comment]
Thank you for your interest in BlendedICU.
We started with MIMIC-IV, eICU, AmsterdamUMCdb, and HiRID in order to pool international data from different hospitals.  Initially, MIMIC-III felt too similar to MIMIC-IV on this aspect. Howver, we will consider adding support to the MIMIC-III database. 
We also welcome pull requests !

**Comment by USM-CHU-FGuyon** [comment]
Hello, MIMIC-III was added in v0.1.0. Do not hesitate to open another issue if needed.

**Comment by Zethson** [comment]
Thank you so much!

We'll try to eventually provide dataloaders for https://github.com/theislab/ehrapy based on your awesome work.
I might come back to you about this.
